### ISSUE TITLE
您好！大佬，这个前端的export const baseURL = 'http://121.4.125.198:9001'中的config未定义，想问一下这个网址还能开放吗

### ISSUE THREAD

**Issue by aboutAQ** [Cpaulyz/CO-IN#7]
![924bd68a0a975823a7884616142f0ed4](https://github.com/user-attachments/assets/e483be3b-47e6-4b77-9e7d-bf8ea43fab2a)

**Comment by Cpaulyz** [comment]
已经过期了，需要自己部署

**Comment by aboutAQ** [comment]
> 已经过期了，需要自己部署

大佬想问一下，config里面是什么呀？可以交流一下吗，这是我的联系方式qq：2859507175
